// flow-typed signature: 4d1e77b599cc85fe5edfb6b2a0b0a62b
// flow-typed version: <<STUB>>/@moltin/sdk_v^2.7.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@moltin/sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@moltin/sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@moltin/sdk/dist/moltin.cjs' {
  declare module.exports: any;
}

declare module '@moltin/sdk/dist/moltin.umd' {
  declare module.exports: any;
}

declare module '@moltin/sdk/rollup.config' {
  declare module.exports: any;
}

declare module '@moltin/sdk/rollup/cjs.config' {
  declare module.exports: any;
}

declare module '@moltin/sdk/rollup/umd.config' {
  declare module.exports: any;
}

declare module '@moltin/sdk/src/config' {
  declare module.exports: any;
}

declare module '@moltin/sdk/src/endpoints/brands' {
  declare module.exports: any;
}

declare module '@moltin/sdk/src/endpoints/cart' {
  declare module.exports: any;
}

declare module '@moltin/sdk/src/endpoints/categories' {
  declare module.exports: any;
}

declare module '@moltin/sdk/src/endpoints/collections' {
  declare module.exports: any;
}

declare module '@moltin/sdk/src/endpoints/currencies' {
  declare module.exports: any;
}

declare module '@moltin/sdk/src/endpoints/gateways' {
  declare module.exports: any;
}

declare module '@moltin/sdk/src/endpoints/orders' {
  declare module.exports: any;
}

declare module '@moltin/sdk/src/endpoints/products' {
  declare module.exports: any;
}

declare module '@moltin/sdk/src/extends/base' {
  declare module.exports: any;
}

declare module '@moltin/sdk/src/extends/catalogue' {
  declare module.exports: any;
}

declare module '@moltin/sdk/src/factories/request' {
  declare module.exports: any;
}

declare module '@moltin/sdk/src/factories/storage' {
  declare module.exports: any;
}

declare module '@moltin/sdk/src/moltin' {
  declare module.exports: any;
}

declare module '@moltin/sdk/src/utils/helpers' {
  declare module.exports: any;
}

declare module '@moltin/sdk/test/factories' {
  declare module.exports: any;
}

declare module '@moltin/sdk/test/unit/authentication' {
  declare module.exports: any;
}

declare module '@moltin/sdk/test/unit/brands' {
  declare module.exports: any;
}

declare module '@moltin/sdk/test/unit/cart' {
  declare module.exports: any;
}

declare module '@moltin/sdk/test/unit/categories' {
  declare module.exports: any;
}

declare module '@moltin/sdk/test/unit/collections' {
  declare module.exports: any;
}

declare module '@moltin/sdk/test/unit/currencies' {
  declare module.exports: any;
}

declare module '@moltin/sdk/test/unit/gateways' {
  declare module.exports: any;
}

declare module '@moltin/sdk/test/unit/orders' {
  declare module.exports: any;
}

declare module '@moltin/sdk/test/unit/products' {
  declare module.exports: any;
}

declare module '@moltin/sdk/test/utils/helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module '@moltin/sdk/dist/moltin.cjs.js' {
  declare module.exports: $Exports<'@moltin/sdk/dist/moltin.cjs'>;
}
declare module '@moltin/sdk/dist/moltin.umd.js' {
  declare module.exports: $Exports<'@moltin/sdk/dist/moltin.umd'>;
}
declare module '@moltin/sdk/rollup.config.js' {
  declare module.exports: $Exports<'@moltin/sdk/rollup.config'>;
}
declare module '@moltin/sdk/rollup/cjs.config.js' {
  declare module.exports: $Exports<'@moltin/sdk/rollup/cjs.config'>;
}
declare module '@moltin/sdk/rollup/umd.config.js' {
  declare module.exports: $Exports<'@moltin/sdk/rollup/umd.config'>;
}
declare module '@moltin/sdk/src/config.js' {
  declare module.exports: $Exports<'@moltin/sdk/src/config'>;
}
declare module '@moltin/sdk/src/endpoints/brands.js' {
  declare module.exports: $Exports<'@moltin/sdk/src/endpoints/brands'>;
}
declare module '@moltin/sdk/src/endpoints/cart.js' {
  declare module.exports: $Exports<'@moltin/sdk/src/endpoints/cart'>;
}
declare module '@moltin/sdk/src/endpoints/categories.js' {
  declare module.exports: $Exports<'@moltin/sdk/src/endpoints/categories'>;
}
declare module '@moltin/sdk/src/endpoints/collections.js' {
  declare module.exports: $Exports<'@moltin/sdk/src/endpoints/collections'>;
}
declare module '@moltin/sdk/src/endpoints/currencies.js' {
  declare module.exports: $Exports<'@moltin/sdk/src/endpoints/currencies'>;
}
declare module '@moltin/sdk/src/endpoints/gateways.js' {
  declare module.exports: $Exports<'@moltin/sdk/src/endpoints/gateways'>;
}
declare module '@moltin/sdk/src/endpoints/orders.js' {
  declare module.exports: $Exports<'@moltin/sdk/src/endpoints/orders'>;
}
declare module '@moltin/sdk/src/endpoints/products.js' {
  declare module.exports: $Exports<'@moltin/sdk/src/endpoints/products'>;
}
declare module '@moltin/sdk/src/extends/base.js' {
  declare module.exports: $Exports<'@moltin/sdk/src/extends/base'>;
}
declare module '@moltin/sdk/src/extends/catalogue.js' {
  declare module.exports: $Exports<'@moltin/sdk/src/extends/catalogue'>;
}
declare module '@moltin/sdk/src/factories/request.js' {
  declare module.exports: $Exports<'@moltin/sdk/src/factories/request'>;
}
declare module '@moltin/sdk/src/factories/storage.js' {
  declare module.exports: $Exports<'@moltin/sdk/src/factories/storage'>;
}
declare module '@moltin/sdk/src/moltin.js' {
  declare module.exports: $Exports<'@moltin/sdk/src/moltin'>;
}
declare module '@moltin/sdk/src/utils/helpers.js' {
  declare module.exports: $Exports<'@moltin/sdk/src/utils/helpers'>;
}
declare module '@moltin/sdk/test/factories.js' {
  declare module.exports: $Exports<'@moltin/sdk/test/factories'>;
}
declare module '@moltin/sdk/test/unit/authentication.js' {
  declare module.exports: $Exports<'@moltin/sdk/test/unit/authentication'>;
}
declare module '@moltin/sdk/test/unit/brands.js' {
  declare module.exports: $Exports<'@moltin/sdk/test/unit/brands'>;
}
declare module '@moltin/sdk/test/unit/cart.js' {
  declare module.exports: $Exports<'@moltin/sdk/test/unit/cart'>;
}
declare module '@moltin/sdk/test/unit/categories.js' {
  declare module.exports: $Exports<'@moltin/sdk/test/unit/categories'>;
}
declare module '@moltin/sdk/test/unit/collections.js' {
  declare module.exports: $Exports<'@moltin/sdk/test/unit/collections'>;
}
declare module '@moltin/sdk/test/unit/currencies.js' {
  declare module.exports: $Exports<'@moltin/sdk/test/unit/currencies'>;
}
declare module '@moltin/sdk/test/unit/gateways.js' {
  declare module.exports: $Exports<'@moltin/sdk/test/unit/gateways'>;
}
declare module '@moltin/sdk/test/unit/orders.js' {
  declare module.exports: $Exports<'@moltin/sdk/test/unit/orders'>;
}
declare module '@moltin/sdk/test/unit/products.js' {
  declare module.exports: $Exports<'@moltin/sdk/test/unit/products'>;
}
declare module '@moltin/sdk/test/utils/helpers.js' {
  declare module.exports: $Exports<'@moltin/sdk/test/utils/helpers'>;
}
